# Generated by Django 6.1 on 2026-09-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("bio", models.TextField(blank=True, max_length=160, null=True)),
                ("avatar", models.CharField(blank=True, max_length=500, null=True)),
                ("banner", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
