# Generated by Django 6.1 on 2026-08-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
